### PR TITLE
Add `packer fmt` formatter

### PR DESCRIPTION
**Pull request by tomeon**
Due to the fact that `packer fmt` accepts only a single file or directory as an argument, this PR includes a not-particularly-pretty wrapper script that calls out to `packer fmt` once per included source file, and a not-particularly-robust mechanism for distinguishing included source files from `packer fmt` options (basically, trying to plop a bare `--` between options and source file arguments).

Also includes some updates to the "Adding new formatters" section of the README; would be happy to spin these changes into a separate PR if that's preferable.

Thanks in advance!

### CODE REVIEW

**Review by zimbatm — COMMENTED** [review]
sounds good. Do you mind also contacting upstream so it eventually gets fixed?

**Comment by tomeon** [comment]
> Do you mind also contacting upstream so it eventually gets fixed?

Done: hashicorp/packer#12883.

**Comment by dawidd6** [comment]
Isn't this the same as `hclfmt` though?

**Comment by zimbatm** [comment]
probably. I would use `hclfmt` as it follows the treefmt spec. But I haven't used Packer for a while, maybe there is some extra semantic that `packer fmt` understands?

**Comment by tomeon** [comment]
> [M]aybe there is some extra semantic that packer fmt understands?

Allegedly several of the `<hashicorp-tool> fmt` subcommands, including `packer fmt`, have tool-specific behavior, according to Hashicorp employees/contributors [here](https://github.com/hashicorp/vscode-hcl/issues/98#issuecomment-1137569350) and [here](https://github.com/hashicorp/vscode-hcl/issues/98#issuecomment-1875159007).

**Pull request merged**
