### PR TITLE
Add support for `nickel format`

### PR DESCRIPTION
**Pull request by gkze**
Have to wrap `nickel` executable because it only accepts one file at a time... I do want to make a PR to Nickel & Topiary to accept multiple file / dir args but want to have something working for now until I do that

### CODE REVIEW

**Comment by gkze** [comment]
🤔 not sure what's up with the (seemingly?) unrelated CI failures...

**Comment by zimbatm** [comment]
Hey thanks. Make sure to also run the  ./examples.sh and `treefmt` to generate the examples and update the README.md

**Comment by zimbatm** [comment]
there is also an unrelated error dues to terraform switching to BSL

**Comment by gkze** [comment]
(sorry for the delay) I tried running examples.sh but am getting various errors - ktlint not having `meta.mainProgram` and `muon-0.2.0` being marked broken. What should we do?

**Comment by gkze** [comment]
Ty!

**Comment by zimbatm** [comment]
I had to move the wrapper out of the options. The default value was depending on `config`, and that doesn't work (the order of evaluation is imports > options > config).

**Comment by gkze** [comment]
That's right - thank you for the help! 🙇🏻

**Pull request merged**
