### PR TITLE
gdformat: Added gdformat

### PR DESCRIPTION
**Pull request by haruki7049**
The gdformat's command, 'gdtoolkit'
https://github.com/Scony/godot-gdscript-toolkit

### CODE REVIEW

**Comment by haruki7049** [comment]
The built is failed therefore I reverted to draft pull request.
The fail appears to have affected the state of support for the platform.
This below log is from a failed CI.

```txt
None failed to evaluate:
error: derivation 'aarch64-darwin.examples' does not have valid outputs: error:
              … while calling the 'getAttr' builtin

                at /derivation-internal.nix:19:19:

                  18|       value = commonAttrs // {
                  19|         outPath = builtins.getAttr outputName strict;
                    |                   ^
                  20|         drvPath = strict.drvPath;

              … while calling the 'derivationStrict' builtin

                at /derivation-internal.nix:9:12:

                   8|
                   9|   strict = derivationStrict drvAttrs;
                    |            ^
                  10|

              (stack trace truncated; use '--show-trace' to show the full trace)

              error: Package ‘godot3-server-3.5.2’ in /nix/store/gzf4zwcakda1nykn6h0avh45xhjhvsz4-source/pkgs/development/tools/godot/3/default.nix:161 is not available on the requested hostPlatform:
                hostPlatform.config = "aarch64-apple-darwin"
                package.meta.platforms = [
                  "i686-linux"
                  "x86_64-linux"
                  "aarch64-linux"
                ]
                package.meta.badPlatforms = [ ]
              , refusing to evaluate.

              a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
                 for a single invocation of the nix tools.

                   $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

                 Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                       then pass `--impure` in order to allow use of environment variables.

              b) For `nixos-rebuild` you can set
                { nixpkgs.config.allowUnsupportedSystem = true; }
              in configuration.nix to override this.

              c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
                { allowUnsupportedSystem = true; }
              to ~/.config/nixpkgs/config.nix.
```

**Comment by haruki7049** [comment]
@Mergifyio refresh

**Comment by haruki7049** [comment]
@Mergifyio update

**Comment by zimbatm** [comment]
thanks!

**Pull request merged**
