### PR TITLE
feat: sqlfluff support

### PR DESCRIPTION
**Pull request by o-az**

### CODE REVIEW

**Comment by o-az** [comment]
current ci failure is because dialect option is not being passed to sqlfluff but it's required

**Comment by zimbatm** [comment]
Our test framework doesn't support options that have no defaults, so I put "ansi" as the default dialect

**Comment by o-az** [comment]
perfect thank you.

**Comment by o-az** [comment]
anything else needed to get this through? Thank you

**Review by zimbatm — APPROVED** [review]
LGTM, thanks

**Pull request merged**
