### PR TITLE
add actionlint

### PR DESCRIPTION
**Pull request by katexochen**
I would like to add [actionlint](https://github.com/rhysd/actionlint) (which is more a linter than a formatter, but I saw that shellcheck seems to be okay, so actionlint should fit, too).

However, I'm facing some problems with the include statements. For some reason, files in the `.github` directory are not included/linted. 

I have provided a test commit that activates actionlint and includes two files that should throw errors, one in `.github`, the other in `github`. Running `nix fmt`, this will only print errors for the non-hidden dir.

@zimbatm is treefmt in general not capable of formatting hidden files?

### CODE REVIEW

**Comment by katexochen** [comment]
I found https://github.com/numtide/treefmt/issues/153

**Comment by zimbatm** [comment]
this is better handled by treefmt2, since it can now use `git ls-files` as a backend

**Comment by katexochen** [comment]
> this is better handled by treefmt2, since it can now use `git ls-files` as a backend

Nice, looking forward to v2. :)

**Comment by Mic92** [comment]
v2 was released.

**Comment by zimbatm** [comment]
Waiting for nixos-unstable to become available: https://nixpk.gs/pr-tracker.html?pr=323172

**Comment by Mic92** [comment]
This now also happened.

**Comment by katexochen** [comment]
see https://github.com/numtide/treefmt-nix/pull/192 :)

**Pull request merged**
